# Generated by Django 4.2.3 on 2023-12-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('address', models.CharField(max_length=150, verbose_name='Endereço')),
                ('complement', models.CharField(max_length=250, verbose_name='Complemento')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('region', models.CharField(max_length=50, verbose_name='Estado/Província')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitude')),
            ],
        ),
    ]
