# Generated by Django 4.2.3 on 2023-07-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
