# Generated by Django 4.2.3 on 2024-03-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristspot',
            old_name='resourses',
            new_name='resources',
        ),
    ]
