# Generated by Django 4.2.3 on 2024-01-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('resourses', models.TextField(verbose_name='Recursos')),
                ('neighborhood', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=150, null=True, verbose_name='País')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pontos_turisticos')),
            ],
        ),
        migrations.DeleteModel(
            name='TourismSpot',
        ),
    ]
