# Generated by Django 4.2.3 on 2023-07-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0002_alter_location_latitude_alter_location_longitude'),
        ('feedback', '0002_feedback_score'),
        ('interested_points', '0003_rename_attraction_resourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('feedbacks', models.ManyToManyField(to='feedback.feedback', verbose_name='Avaliações')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Localização')),
                ('resourses', models.ManyToManyField(to='interested_points.resourse', verbose_name='Recursos')),
            ],
        ),
    ]
