# Generated by Django 4.2.3 on 2023-12-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourist_resources', '0001_initial'),
        ('feedback', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('feedbacks', models.ManyToManyField(to='feedback.feedback', verbose_name='Avaliações')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Localização')),
                ('resourses', models.ManyToManyField(to='tourist_resources.resourse', verbose_name='Recursos')),
            ],
        ),
    ]
