# Generated by Django 4.2.3 on 2023-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismspots',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
    ]
