# Generated by Django 4.2.3 on 2023-07-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tourismspots_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourismSpots',
            new_name='TourismSpot',
        ),
    ]
