# Generated by Django 4.2.3 on 2023-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interested_points', '0003_rename_attraction_resourse'),
        ('core', '0003_rename_tourismspots_tourismspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismspot',
            name='resourses',
            field=models.ManyToManyField(to='interested_points.resourse'),
        ),
    ]
