# Generated by Django 4.2.3 on 2023-07-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interested_points', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestedPoint',
            new_name='Attraction',
        ),
    ]
