# Generated by Django 4.2.3 on 2023-07-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interested_points', '0002_rename_interestedpoint_attraction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attraction',
            new_name='Resourse',
        ),
    ]
