# Generated by Django 4.2.3 on 2023-12-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('operating_hours', models.TextField(verbose_name='Horário de funcionamento')),
                ('age_required', models.IntegerField(default=0, verbose_name='Idade Mínima')),
            ],
        ),
    ]
